INSERT INTO zones (
    name,
    points,
    mode,
    camera_id,
    empty_timeout,
    full_timeout,
    empty_threshold,
    full_threshold,
    max_out_time,
    email_cooldown,
    enabled,
    active,
    description,
    created_at,
    updated_at,
    deleted_at,
    color,
    tags,
    snapshot_path,
    metadata
) VALUES (
    'Sistema (Placeholder)',
    '[[0.01, 0.01], [0.02, 0.01], [0.02, 0.02], [0.01, 0.02]]',
    'occupancy',
    13,
    5,
    10,
    0,
    3,
    30,
    600,
    true,
    true,
    'Zona técnica para manter stream ativo - NÃO DELETAR',
    NOW(),
    NOW(),
    NULL,
    '#000000',
    ARRAY['system', 'placeholder']::text[],
    NULL,
    '{"system_zone": true, "invisible": true}'::jsonb
);
